language: scala
scala:
- 2.11.1
env:
  global:
    secure: n9gDbTmZPjMr5dJiUUiZiV4L9ZScQH1+/8Hij7zYWxlDI0A0+dEApP2aIIfLWo55/RC0vETgdxRxElY6Gd5stcIIlJtk4zfSkY6cWryk7JcPJIWcOvMg3Kqlk9DSRWVg8RBLxjFC8FfKyOFGzx+uQH4gEOv09FrFX8taeXiblx8=
script:
- if [[ "$TRAVIS_PULL_REQUEST" == 'false' && "$TRAVIS_BRANCH" == 'master' ]] ; then
  ./deploy.bash ; else ./dist.bash ; fi
